from django.conf.urls.defaults import *

urlpatterns = patterns('statistics.views',
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/year/(?P<year>\d{4,4})/week/(?P<week>\d{1,2})/$', 'week'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/year/(?P<year>\d{4,4})/month/(?P<month>\d{1,2})/$', 'month'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/week/$', 'todays_week'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/month/$', 'todays_month'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/date/$', 'date'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/date/selection/$', 'date_selection_form'),
    (r'^(?P<search>(user|team))/(?P<search_id>\d+)/date/(?P<start_date>[0-9-]+)/(?P<end_date>[0-9-]+)/$', 'date_selection_display'),
    (r'^team_stat/(?P<team_id>\d+)/year/(?P<year>\d{4,4})/week/(?P<week>\d{1,2})/$', 'show_team_week'),
    (r'^team_stat/(?P<team_id>\d+)/year/(?P<year>\d{4,4})/month/(?P<month>\d{1,2})/$', 'show_team_month'),
    (r'^team_stat/(?P<team_id>\d+)/date/selection/$', 'team_date_selection_form'),
    (r'^team_stat/(?P<team_id>\d+)/date/(?P<start_date>[0-9-]+)/(?P<end_date>[0-9-]+)/$', 'team_date_selection_display'),
    (r'^data/(?P<search>(user|team))/(?P<search_id>\d+)/date/(?P<start_date>[0-9-]+)/(?P<end_date>[0-9-]+)/$', 'get_date_data'),
    (r'^data/(?P<search>(user|team))/(?P<search_id>\d+)/year/(?P<year>\d{4,4})/(?P<action>(week|month))/(?P<data>\d{1,2})/$', 'get_data'),
    (r'^data/team_stat/(?P<team_id>\d+)/year/(?P<year>\d{4,4})/week/(?P<week>\d{1,2})/$', 'get_team_week_data'),
    (r'^data/team_stat/(?P<team_id>\d+)/year/(?P<year>\d{4,4})/month/(?P<month>\d{1,2})/$', 'get_team_month_data'),
    (r'^data/team_stat/(?P<team_id>\d+)/date/(?P<start_date>[0-9-]+)/(?P<end_date>[0-9-]+)/$', 'get_team_date_data'),
)
